/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OORestaurants;
import java.awt.Component;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Elmar
 */
public class OO_Restaurants extends javax.swing.JFrame {

    /**
     * Creates new form OO_Restaurants
     */
    public OO_Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlblTax3 = new javax.swing.JLabel();
        jlblTax4 = new javax.swing.JLabel();
        jlblSubTotal2 = new javax.swing.JLabel();
        jlblTotal2 = new javax.swing.JLabel();
        jtxtChickenLegend = new javax.swing.JTextField();
        jtxtChickenBurger = new javax.swing.JTextField();
        jtxtFiletOFish = new javax.swing.JTextField();
        jlblTotal3 = new javax.swing.JLabel();
        jlblTotal4 = new javax.swing.JLabel();
        jtxtChickenBurgerM = new javax.swing.JTextField();
        jtxtBaconCheeseBurger = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnReceipt = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jlblTax2 = new javax.swing.JLabel();
        jtxtMilkShake = new javax.swing.JTextField();
        jtxtVanillaCone = new javax.swing.JTextField();
        jtxtClassicVanilla = new javax.swing.JTextField();
        jtxtVanillaMilkShake = new javax.swing.JTextField();
        jtxtChocMilkShake = new javax.swing.JTextField();
        jlblTotal5 = new javax.swing.JLabel();
        jlblTotal6 = new javax.swing.JLabel();
        jlblTotal7 = new javax.swing.JLabel();
        jlblTax5 = new javax.swing.JLabel();
        jlblSubTotal3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jtxtCostMeal = new javax.swing.JTextField();
        jtxtCostDrink = new javax.swing.JTextField();
        jtxtCostTotalCost = new javax.swing.JTextField();
        jlblTax6 = new javax.swing.JLabel();
        jlblSubTotal4 = new javax.swing.JLabel();
        jlblTotal8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Managment System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1330, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblTax3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jlblTax3.setText("Meals");

        jlblTax4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax4.setText("Filet-O-Fish");

        jlblSubTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal2.setText("Chicken Burger");

        jlblTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal2.setText("Chicken Legend");

        jtxtChickenLegend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenLegend.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenLegend.setText("0");
        jtxtChickenLegend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenLegendActionPerformed(evt);
            }
        });

        jtxtChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurger.setText("0");

        jtxtFiletOFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFiletOFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFiletOFish.setText("0");
        jtxtFiletOFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiletOFishActionPerformed(evt);
            }
        });

        jlblTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal3.setText("Chicken Burger Meal");

        jlblTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal4.setText("Bacon and Cheese Burger");

        jtxtChickenBurgerM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurgerM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurgerM.setText("0");

        jtxtBaconCheeseBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBaconCheeseBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBaconCheeseBurger.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblSubTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblTax4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jlblTax3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlblTotal4)
                            .addComponent(jlblTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtBaconCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtxtFiletOFish, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtChickenBurger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtChickenLegend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtChickenBurgerM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTax3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblTax4)
                    .addComponent(jtxtFiletOFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubTotal2)
                    .addComponent(jtxtChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTotal2)
                    .addComponent(jtxtChickenLegend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jlblTotal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTotal4)
                            .addComponent(jtxtBaconCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jtxtChickenBurgerM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 450, 250));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jbtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReceipt.setText("Receipt");
        jbtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jbtnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTotal)
                    .addComponent(jbtnExit)
                    .addComponent(jbtnReset)
                    .addComponent(jbtnReceipt))
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 910, 70));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setText("Tax");

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setText("SubTotal");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setText("Total");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal)
                    .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 450, 170));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jlblTax2.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jlblTax2.setText("Drinks");

        jtxtMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMilkShake.setText("0");
        jtxtMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMilkShakeActionPerformed(evt);
            }
        });

        jtxtVanillaCone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanillaCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanillaCone.setText("0");

        jtxtClassicVanilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtClassicVanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtClassicVanilla.setText("0");
        jtxtClassicVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtClassicVanillaActionPerformed(evt);
            }
        });

        jtxtVanillaMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanillaMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanillaMilkShake.setText("0");

        jtxtChocMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChocMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChocMilkShake.setText("0");

        jlblTotal5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal5.setText("Chocolate Millk Shake");

        jlblTotal6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal6.setText("Vanilla Milk Shake");

        jlblTotal7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal7.setText("Classic Vanilla");

        jlblTax5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax5.setText("Milk Shake");

        jlblSubTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal3.setText("Vanilla Cone");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jlblTax2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jtxtVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jlblSubTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(67, 67, 67))
                            .addComponent(jlblTax5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlblTotal6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblTotal5)
                            .addComponent(jlblTotal7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtClassicVanilla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtVanillaMilkShake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtChocMilkShake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(195, 195, 195))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTax2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtVanillaCone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubTotal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtClassicVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlblTotal6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblTotal5)
                            .addComponent(jtxtChocMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jtxtVanillaMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 450, 250));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(924, 180, 420, 510));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtCostMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtCostDrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jtxtCostTotalCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlblTax6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax6.setText("Cost of Meal");

        jlblSubTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal4.setText("Cost of Drinks");

        jlblTotal8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal8.setText("Total Cost of Items");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblTotal8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblSubTotal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTax6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCostTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCostDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax6))
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubTotal4)
                    .addComponent(jtxtCostDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCostTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotal8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 450, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        SubClass_Child ItemCost = new SubClass_Child();
        
        double iTax, iSubTotal, iTotal ;
        
        ItemCost.Filet_O_Fish = ItemCost.pFilet_O_Fish * Double.parseDouble(jtxtFiletOFish.getText());
        ItemCost.ChickenBurger = ItemCost.pChickenBurger * Double.parseDouble(jtxtChickenBurger.getText());
        ItemCost.ChickenLegend = ItemCost.pChickenLegend * Double.parseDouble(jtxtChickenLegend.getText());
        ItemCost.ChickenBurgerM = ItemCost.pChickenBurgerM * Double.parseDouble(jtxtChickenBurgerM.getText());
        ItemCost.BaconCheeseBurger = ItemCost.pBaconCheeseBurger * Double.parseDouble(jtxtBaconCheeseBurger.getText());
        
        
        ItemCost.MilkShake = ItemCost.pMilkShake * Double.parseDouble(jtxtMilkShake.getText());
        ItemCost.VanillaCone = ItemCost.pVanillaCone * Double.parseDouble(jtxtVanillaCone.getText());
        ItemCost.ClasVanilla = ItemCost.pClasVanilla * Double.parseDouble(jtxtClassicVanilla.getText());
        ItemCost.VanMilkShake = ItemCost.pVanMilkShake * Double.parseDouble(jtxtVanillaMilkShake.getText());
        ItemCost.ChocMilkShake = ItemCost.pChocMilkShake * Double.parseDouble(jtxtChocMilkShake.getText());
        
        
        iSubTotal = ItemCost.GetAmount();
        iTax = ItemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax;
        
        
        String SubTotal = String.format("£%.2f", iSubTotal);
        jtxtSubTotal.setText(SubTotal);
        
        String Tax = String.format("£%.2f", iTax);
        jtxtTax.setText(Tax);
        
        String Total = String.format("£%.2f", iTotal);
        jtxtTotal.setText(Total);
        
        
        String Meal = String.format("£%.2f", ItemCost.Meals);
        jtxtCostMeal.setText(Meal);
        
        String Drink = String.format("£%.2f", ItemCost.Drinks);
        jtxtCostDrink.setText(Drink);
        
        String TotalCost = String.format("£%.2f", ItemCost.TotalofMD);
        jtxtCostTotalCost.setText(TotalCost);
        
        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        SubClass_Child iExit = new SubClass_Child();
        iExit.iExitSystem();
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
    JTextField cleartext = null ;
    
    for (Component c:jPanel4.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext = (JTextField) c ;
        cleartext.setText("0");
    }
    }
    
    for (Component c:jPanel3.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext = (JTextField) c ;
        cleartext.setText("0");
    }
    }
    
    for (Component c:jPanel6.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext = (JTextField) c ;
        cleartext.setText("");
    }
    }
    
    for (Component c:jPanel8.getComponents()){
    if (c.getClass().toString().contains("javax.swing.JTextField")){
        cleartext = (JTextField) c ;
        cleartext.setText("");
    }
    }
    jtxtReceipt.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReceiptActionPerformed

        int refs = 1325 + (int) (Math.random()*4238);
        
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
        
        
        
                 jtxtReceipt.append("\tRestaurant Management Systems:\n" + 
                         "Reference:\t\t\t" + refs + 
                "\n=====================================\n" + 
                        "Meals:\t\t" + jtxtCostMeal.getText() + "\n\n" + 
                         "Drinks:\t\t" + jtxtCostDrink.getText() + "\n\n" + 
                        "Cost of Items:\t" + jtxtCostTotalCost.getText() + "\n\n" + 
                 "=====================================" + "\n\n" + 
                 "Tax:\t\t" + jtxtTax.getText() + "\n\n" + 
                         "Subtotal:\t" + jtxtSubTotal.getText() + "\n\n" + 
                         "Total:\t\t" + jtxtTotal.getText() + "\n" +
                         
                         
            "=====================================" + 
            "\nDate: " + Tdate.format(timer.getTime()) + 
                "\tTime: " + tTime.format(timer.getTime()) + 
            "\n\n\t\tThank you ");
                         
        
    }//GEN-LAST:event_jbtnReceiptActionPerformed

    private void jtxtFiletOFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiletOFishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiletOFishActionPerformed

    private void jtxtChickenLegendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenLegendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenLegendActionPerformed

    private void jtxtMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMilkShakeActionPerformed

    private void jtxtClassicVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtClassicVanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtClassicVanillaActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.IllegalAccessException
     * @throws java.lang.InstantiationException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OO_Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReceipt;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblSubTotal2;
    private javax.swing.JLabel jlblSubTotal3;
    private javax.swing.JLabel jlblSubTotal4;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTax2;
    private javax.swing.JLabel jlblTax3;
    private javax.swing.JLabel jlblTax4;
    private javax.swing.JLabel jlblTax5;
    private javax.swing.JLabel jlblTax6;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblTotal2;
    private javax.swing.JLabel jlblTotal3;
    private javax.swing.JLabel jlblTotal4;
    private javax.swing.JLabel jlblTotal5;
    private javax.swing.JLabel jlblTotal6;
    private javax.swing.JLabel jlblTotal7;
    private javax.swing.JLabel jlblTotal8;
    private javax.swing.JTextField jtxtBaconCheeseBurger;
    private javax.swing.JTextField jtxtChickenBurger;
    private javax.swing.JTextField jtxtChickenBurgerM;
    private javax.swing.JTextField jtxtChickenLegend;
    private javax.swing.JTextField jtxtChocMilkShake;
    private javax.swing.JTextField jtxtClassicVanilla;
    private javax.swing.JTextField jtxtCostDrink;
    private javax.swing.JTextField jtxtCostMeal;
    private javax.swing.JTextField jtxtCostTotalCost;
    private javax.swing.JTextField jtxtFiletOFish;
    private javax.swing.JTextField jtxtMilkShake;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtVanillaCone;
    private javax.swing.JTextField jtxtVanillaMilkShake;
    // End of variables declaration//GEN-END:variables
}
